version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - qdrant_network

  redis:
    image: redis:7.2-bookworm
    container_name: redis
    ports:
      - "6480:6379"
    networks:
      - qdrant_network
    depends_on:
      - qdrant

  uvicorn_app:
    build: .
    container_name: uvicorn
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src # Mount your local folder to /src in the container
    networks:
      - qdrant_network
    depends_on:
      - qdrant

volumes:
  qdrant_data:

networks:
  qdrant_network:
    driver: bridge
